@startuml
'Actors
|U| Usuario
|B| Bot

|U|
start
:Usuario accede al bot;
|B|
:Muestra las opciones de uso;
|U|
if (El alumno selecciona una opción) then (ver las configuraciones)
    :EL sistema muestra
    la vista de configuración;
    detach
endif
->elige ver los\n proceso vigentes;
|B|
:Muestra los procesos vigentes;
|U|
:El alumno selecciona\nun proceso vigente;
:Selecciona la opción de consultas;
|B|
:Muestra las opciones de consultas disponibles;
|U|
switch (Elige que ver)
case (definición)
  :Elige ver\nla definición;
case ( fechas )
  :Elige ver\nlas fechas;
case (\ncontactos)
  :Elige ver\nla los roles\ny contactos;
case ( requisitos )
  ::Elige ver\nla Requisitos;;
case ( FAQ )
  :Elige ver\nel FAQ;
endswitch
|B|
: El sistema muestra
la información deseada
de forma concisa
y un enlace a la página de ayuda;
:El sistema muestra
la opción de valorar la consulta;
|U|
:El alumno evalúa la respuesta;
|B|
:El sistema almacena
la valoración del alumno;
:El sistema le muestra
la opción de contactar
a un asistente;
|U|
if (El alumno evalúa \ncontactar a un asistente) then (elige no contactarlo)
stop
endif
-> Decide si contactarlo;
|B|
:EL bot notifica a los administradores;
detach
@enduml